# Generated by Django 3.1.7 on 2021-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210526_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
